sudo: required
group: deprecated-2017Q2

services:
- docker

script:
- docker run --user $(id -u):$(id -g) --volume $(pwd):/home/builder/stockfish.js:rw niklasf/emscripten-for-stockfish

deploy:
  provider: releases
  api_key:
    secure: vMf25I6rGVDgCA2cMXLhCva50Vda3276Cljad1hnZjJ2ZiGQluQ8pikDWeJXqznA4tto2GUUcVArI4COZWXMrF+BI50q6A1joNPDmZNEGSu4+gTDurrVekAzvJnwwddsUZos+9eOO+PE9KuqbFbacH2qk/OA8B8SxpEWQy6AUGeAZvbp/H6JVwObuV3moTfIilfRjXDlDXZ2jqcmwxIqgGBbcb3U/u/wz/7AeuJfGWPN2JiJYobz/dCPmXOKJ0JRkPkram5P/CTjMyJ1yB7vbThIclfRmt19LsRvBQNXhkHNnlIKcSM7fCiBmNQ2yjf+9nn4qb7n9JVrUD0aKF1FQSsTVBgvGdnw3/Sb2gGDykQ4kJD+6aIy1KW4KBd2OfiZitPcTqjRocx/4sv0EyGBj2IDFuXhC7lrOrYygsZA48a7PhDmSuV1TpsKp3WgNUxEVr9S0EHdT2YnkSa8emVuEHPvl/bfFisnfG3SZpQfxdIy4CuT9L7tadaMwxTtYT226qVNBE/3NOJwanX7FvtVjdTUALt9Q3XunvpYMU4h1TM5/7ic5qMyehdbD3nU5im2muLZnGbaqzolZ72nxS1IGW2jhAyOJyyC3/PzDid2b1U6bmStfF87NkVfygi0dHRD3XA1ia03+CHoabDETt28hIs4IeKshLOgutsXNG/acmI=
  file:
   - stockfish.js
   - stockfish.wasm
   - stockfish.wasm.js
  skip_cleanup: true
  on:
    tags: true
    repo: niklasf/stockfish.js
    branch: ddugovic
